# Membaca Data dari __Excel__

Data yang kita temui sehari-hari biasanya memiliki format `.xlsx` atau `.xls`. Sekarang kita  akan _import_ data dari __Excel__ untuk masuk ke dalam __R__.

_Library_ yang digunakan adalah `library(readxl)`

Contoh [data yang digunakan](https://github.com/ikanx101/belajaR/blob/master/Materi%20Training/Day%201%20-%20R%20Series/Contoh_Data.xlsx):

```{r}
library(readxl)
data = read_excel('Contoh_Data.xlsx')
head(data)
```

## Membaca Data dari Format File Lain

__R__ memiliki kemampuan untuk membaca data dalam format lain seperti `csv`, `sav` (SPSS), `txt`, dan lainnya. Secara _default_, __R__ bisa membaca file dalam bentuk `csv` dan `txt` tanpa menggunakan `library()` lainnya.

Gunakan fungsi `read.csv()` untuk membaca file `csv` dan `readLines()` untuk file `txt`.


## Membuat Data Sintetis untuk Keperluan _Training_

Untuk keperluan _training_ ini, kita akan membuat satu _dataset_ sintetis yang kemudian kita akan jadikan contoh pada bagian _data carpentry_.

### Contoh Data

_Dataset_ ini akan berisi data hasil survey dengan variabel-variabel berikut:

1. `id_responden`.
1. `gender`: jenis kelamin responden. Berisi dua kategori: `pria` dan `wanita` dengan proporsi `50:50`.
1. `usia`: usia responden. Berisi angka dari _range_ `17-50` tahun.
1. `awareness`: _awareness_ responden terhadap produk. Berisi dua kategori: `Ya` dan `Tidak` dengan proporsi `70:30`.











