project:
  type: book

book:
  title: "Intro To R - Volume 4"
  subtitle: "Sebuah Modul Training"
  author: "Ikang Fadhli"
  date: "Maret 2024"
  chapters:
    - index.qmd
    - bab_1.qmd
    - bab_2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

