# Kata Pengantar {.unnumbered}

Sudah dua tahun sejak saya mempublikasikan modul _training_ __Intro to R - Volume 3__ di kalangan internal Nutrifood dan ITB. Ada berbagai tanggapan yang saya terima dan semuanya memiliki sentimen positif.

Sejak saat itu banyak perubahan dan perkembangan dalam dunia data sains, termasuk pada __R__, misalnya:

1. Berubahnya haluan __R Studio__ menjadi __Posit__. Akibatnya __Posit__ kini tak hanya bisa digunakan oleh _useR_ tapi juga oleh pawang ular.
1. Munculnya __Quarto__ sebagai calon penerus __R Markdown__ dan _libraries_ sejenisnya.
1. Penerapan _generative AI_ yang semakin meluas, termasuk penggunaan __Hugging Face__ sebagai _marketplace_ untuk model-model AI.
1. Penggunaan _meta heuristic optimization algorithm_ untuk model _reinforce learning_.

Oleh karena itu, saya mencoba meng-_update_ modul _training_ ini agar tetap relevan.

Ikang Fadhli.

ikanx101.com

# Cara Membaca dan Menggunakan Buku Ini

Pada buku ini, disertakan penjelasan dan skrip __R__ yang bisa dicoba langsung. Setiap skrip yang _executable_ memiliki _shading_ berwarna abu-abu di setiap barisnya.

# Untuk apa saya belajar __R__? {.unnumbered}

Di era digitalisasi ini, disadari atau tidak data tersebar di mana-mana. Data juga dihasilkan dengan _volume_ yang besar dalam waktu singkat. 

> _Analoginya seperti ada sungai yang memiliki arus yang deras dan kencang._
Seperti itulah kondisi saat ini.

_Tools_ analisa data klasik seperti __Ms. Excel__ dan __SPSS__ sudah tidak mampu lagi melakukan analisa _big data_ yang seringkali berbentuk _unstructured data_.

__R__ tidak sendirian, ada juga _software_ lain bernama __Python__. Keduanya digunakan untuk membuat algoritma _artificial intelligence_ (bahasa keren dari _machine learning_. Bahasa kerennya dari _computational science_).

