project:
  type: book

book:
  title: "Intro To R - Volume 4"
  subtitle: "Sebuah Modul Training"
  author: "Ikang Fadhli"
  date: "14/03/2024"
  chapters:
    - index.qmd
    - 1 how to.qmd
    - 2 why.qmd
    - 3 part 1.qmd
    - 3 part 2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt